# Generated by Django 5.0.3 on 2024-03-20 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HiringManager',
            fields=[
                ('name', models.CharField(max_length=35)),
                ('lastName', models.CharField(max_length=35)),
                ('identification', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('password1', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HiringLeader',
            fields=[
                ('name', models.CharField(max_length=35)),
                ('lastName', models.CharField(max_length=35)),
                ('identification', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('password1', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('hiringManagers', models.ManyToManyField(related_name='hiringManager_list_to_a_leader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('name', models.CharField(max_length=35)),
                ('lastName', models.CharField(max_length=35)),
                ('identification', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('password1', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('hiringManagersList', models.ManyToManyField(related_name='hiringManager_list_to_the_administrator', to=settings.AUTH_USER_MODEL)),
                ('hiringLeaders', models.ManyToManyField(related_name='hiringLeader_list', to='login.hiringleader')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
