# Generated by Django 5.0.3 on 2024-03-10 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_user_groups_remove_user_user_permissions_and_more'),
        ('petition', '0003_alter_petition_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
