# Generated by Django 5.0.3 on 2024-03-10 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('login', '0004_delete_user'),
        ('petition', '0003_alter_petition_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCustom',
            new_name='User',
        ),
    ]
