# Generated by Django 5.0.2 on 2024-03-05 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('state', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('en_proceso', 'En Proceso'), ('rechazado', 'Rechazado')], max_length=20)),
                ('cenco', models.CharField(max_length=20)),
                ('fullName', models.CharField(max_length=255)),
                ('identityDocument', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petitionUser', to='login.user')),
            ],
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('petition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='petition.petition')),
                ('hasMoneyInCenco', models.BooleanField(default=False)),
                ('cencoResponsible', models.CharField(max_length=255)),
                ('monitoringType', models.CharField(choices=[('academica', 'Academica'), ('oficina', 'Oficina')], max_length=20)),
                ('studentCode', models.CharField(max_length=20)),
                ('daviPlata', models.CharField(max_length=20)),
                ('projectOrCourse', models.CharField(max_length=255)),
                ('monitoringDescription', models.TextField()),
                ('hoursPerWeek', models.PositiveIntegerField()),
                ('totalPaymentAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isOneTimePayment', models.BooleanField(default=False)),
            ],
            bases=('petition.petition',),
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('petition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='petition.petition')),
                ('personType', models.CharField(choices=[('serviceProvision', 'ServiceProvision'), ('practicing', 'Practicing')], max_length=50)),
                ('requesterName', models.CharField(max_length=255)),
                ('requesterFaculty', models.CharField(max_length=255)),
                ('motive', models.CharField(max_length=255)),
                ('bankEntity', models.CharField(max_length=255)),
                ('bankAccountType', models.CharField(choices=[('Ahorro', 'Ahorro'), ('Corriente', 'Corriente')], max_length=50)),
                ('bankAccountNumber', models.CharField(max_length=50)),
                ('eps', models.CharField(max_length=255)),
                ('pensionFund', models.CharField(max_length=255)),
                ('arl', models.CharField(max_length=255)),
                ('contractValue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentInfo', models.TextField()),
                ('rutAttachment', models.FileField(upload_to='rut_attachments/')),
            ],
            bases=('petition.petition',),
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('author', models.CharField(max_length=50)),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='petition.petition')),
            ],
        ),
    ]
