# Generated by Django 5.0.3 on 2024-03-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0003_alter_petition_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='rutAttachment',
            field=models.FileField(upload_to='rut/'),
        ),
    ]
