# Generated by Django 5.0.3 on 2024-03-29 20:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0005_alter_petition_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoring',
            options={'verbose_name': 'Monitoria', 'verbose_name_plural': 'Monitorias'},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'verbose_name': 'Observación', 'verbose_name_plural': 'Observaciones'},
        ),
        migrations.AlterModelOptions(
            name='other',
            options={'verbose_name': 'Otro tipo', 'verbose_name_plural': 'Otros tipos'},
        ),
        migrations.AlterModelOptions(
            name='petition',
            options={'verbose_name': 'Petición', 'verbose_name_plural': 'Peticiones'},
        ),
        migrations.AddField(
            model_name='petition',
            name='userAsigner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userAsigner', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignador'),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='cencoResponsible',
            field=models.CharField(max_length=255, verbose_name='Responsable de CENCO'),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='daviPlata',
            field=models.CharField(max_length=20, verbose_name='DaviPlata'),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='hasMoneyInCenco',
            field=models.BooleanField(default=False, verbose_name='¿Tiene dinero en CENCO?'),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='hoursPerWeek',
            field=models.PositiveIntegerField(verbose_name='Horas por semana'),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='isOneTimePayment',
            field=models.BooleanField(default=False, verbose_name='Es un pago único'),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='monitoringDescription',
            field=models.TextField(verbose_name='Descripción del monitoreo'),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='monitoringType',
            field=models.CharField(choices=[('academica', 'Académica'), ('oficina', 'Oficina')], max_length=20, verbose_name='Tipo de Monitoreo'),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='projectOrCourse',
            field=models.CharField(max_length=255, verbose_name='Proyecto o Curso'),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='studentCode',
            field=models.CharField(max_length=20, verbose_name='Código de estudiante'),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='totalPaymentAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto total de pago'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='author',
            field=models.CharField(max_length=50, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='petition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='petition.petition', verbose_name='Petición'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='time',
            field=models.TimeField(verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='other',
            name='arl',
            field=models.CharField(max_length=255, verbose_name='ARL'),
        ),
        migrations.AlterField(
            model_name='other',
            name='bankAccountNumber',
            field=models.CharField(max_length=50, verbose_name='Número de Cuenta Bancaria'),
        ),
        migrations.AlterField(
            model_name='other',
            name='bankAccountType',
            field=models.CharField(choices=[('Ahorro', 'Ahorro'), ('Corriente', 'Corriente')], max_length=50, verbose_name='Tipo de Cuenta Bancaria'),
        ),
        migrations.AlterField(
            model_name='other',
            name='bankEntity',
            field=models.CharField(max_length=255, verbose_name='Entidad Bancaria'),
        ),
        migrations.AlterField(
            model_name='other',
            name='contractValue',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor del Contrato'),
        ),
        migrations.AlterField(
            model_name='other',
            name='eps',
            field=models.CharField(max_length=255, verbose_name='EPS'),
        ),
        migrations.AlterField(
            model_name='other',
            name='motive',
            field=models.CharField(max_length=255, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='other',
            name='paymentInfo',
            field=models.TextField(verbose_name='Información de Pago'),
        ),
        migrations.AlterField(
            model_name='other',
            name='pensionFund',
            field=models.CharField(max_length=255, verbose_name='Fondo de Pensiones'),
        ),
        migrations.AlterField(
            model_name='other',
            name='personType',
            field=models.CharField(choices=[('serviceProvision', 'Prestación de Servicios'), ('practicing', 'Practicante')], max_length=50, verbose_name='Tipo de Petición'),
        ),
        migrations.AlterField(
            model_name='other',
            name='requesterFaculty',
            field=models.CharField(max_length=255, verbose_name='Facultad del solicitante'),
        ),
        migrations.AlterField(
            model_name='other',
            name='requesterName',
            field=models.CharField(max_length=255, verbose_name='Nombre del solicitante'),
        ),
        migrations.AlterField(
            model_name='other',
            name='rutAttachment',
            field=models.FileField(upload_to='rut/', verbose_name='Adjunto RUT'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='cenco',
            field=models.CharField(max_length=20, verbose_name='Centro de Costo'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='endDate',
            field=models.DateField(verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='fullName',
            field=models.CharField(max_length=255, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='identityDocument',
            field=models.CharField(max_length=20, verbose_name='Documento de identidad'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='petitionDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de solicitud'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='phoneNumber',
            field=models.CharField(max_length=15, verbose_name='Número de teléfono'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='startDate',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='state',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('en_proceso', 'En Proceso'), ('rechazado', 'Rechazado')], max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petitionUser', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
