# Generated by Django 5.0.4 on 2024-04-28 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0006_alter_monitoring_options_alter_observation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('isComplete', models.BooleanField(default=False, verbose_name='')),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='petition.petition', verbose_name='Petición')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
            },
        ),
        migrations.CreateModel(
            name='TaskPredeterminate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('isComplete', models.BooleanField(default=False, verbose_name='')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskAdmin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea Predeterminada',
                'verbose_name_plural': 'Tareas Predeterminadas',
            },
        ),
    ]
