# Generated by Django 5.0.4 on 2024-04-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0007_task_taskpredeterminate'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='percentage',
            field=models.IntegerField(default=0, verbose_name='Porcentaje'),
        ),
    ]
