# Generated by Django 5.0.4 on 2024-04-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0009_alter_observation_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='petitionDate',
            field=models.DateField(verbose_name='Fecha de solicitud'),
        ),
    ]
