# Generated by Django 5.0.4 on 2024-05-06 05:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0012_notification_time_alter_notification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='petition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='petition.petition', verbose_name='Petición'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.TimeField(null=True, verbose_name='Hora'),
        ),
    ]
