# Generated by Django 5.0.4 on 2024-05-20 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0013_alter_notification_date_alter_notification_petition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petitionUser', to=settings.AUTH_USER_MODEL, verbose_name='Asignar a gestor'),
        ),
    ]
