name: Django Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django
        pip install dj_database_url 
        pip install psycopg2-binary
        pip install whitenoise
        pip install selenium

    - name: Set up sqlite3
      run: |
        python manage.py migrate

    - name: Run Server
      run: |
        python manage.py runserver &
        sleep 5 # Espera un tiempo suficiente para que el servidor se inicie completamente.

    - name: Run Unit tests
      run: |
        python manage.py test tests/UnitTests

    - name: Run Selenium tests
      run: |
        python manage.py test tests/sel

    - name: Stop Django server
      run: |
        kill $(lsof -t -i:8000) # Detiene el servidor Django que se ejecuta en el puerto 8000.
