# Generated by Django 5.0.4 on 2024-05-05 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='actor_content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='obj_id_actor',
        ),
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actor_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
